### ISSUE TITLE
[runtime issue] fatal: morestack on g0

### ISSUE THREAD

**Issue by bweston92** [gographics/imagick#130]
I'm attempting to run my test, that is panicking. Any help is appreciated.

It is running inside a container defined by the following:
```
FROM golang:1.8-alpine
RUN apk update && apk add git openssh gcc libc-dev musl-dev imagemagick imagemagick-dev
```

The subject file:
```
package main

import (
	"gopkg.in/gographics/imagick.v2/imagick"
)

func init() {
	imagick.Initialize()
}

func transformSvgToPng(s []byte) ([]byte, error) {
	mw := imagick.NewMagickWand()
	defer mw.Destroy()

	mw.ReadImageBlob(s)
	mw.SetImageFormat("PNG")

	return mw.GetImageBlob(), nil
}
```

The test file:
```
package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func Test_transformSvgToPng_HasPngHeader(t *testing.T) {
	r, _ := transformSvgToPng([]byte(exampleSVGContent))

	// Header spec: https://www.w3.org/TR/PNG-Structure.html
	assert.Equal(t, byte(0x89), r[0])
	assert.Equal(t, byte(0x50), r[1])
	assert.Equal(t, byte(0x4e), r[2])
	assert.Equal(t, byte(0x47), r[3])
	assert.Equal(t, byte(0xd), r[4])
	assert.Equal(t, byte(0xa), r[5])
	assert.Equal(t, byte(0x1a), r[6])
	assert.Equal(t, byte(0xa), r[7])
}
```

Issue I'm receiving.
```
fatal: morestack on g0
SIGTRAP: trace trap
PC=0x46ce22 m=3 sigcode=128
signal arrived during cgo execution

goroutine 103 [syscall, locked to thread]:
runtime.cgocall(0x8fd9c0, 0xc420148e30, 0xa39ede)
        /usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc420148df0 sp=0xc420148db0
gopkg.in/gographics/imagick.v2/imagick._Cfunc_MagickReadImageBlob(0x1eadee0, 0xc42014c340, 0x194, 0x0)
        gopkg.in/gographics/imagick.v2/imagick/_obj/_cgo_gotypes.go:7028 +0x4d fp=0xc420148e30 sp=0xc420148df0
gopkg.in/gographics/imagick.v2/imagick.(*MagickWand).ReadImageBlob.func1(0xc42014c340, 0x194, 0x1a0, 0x1eadee0, 0xc42014c340, 0x194, 0xc420148ed8)
        /go/src/gopkg.in/gographics/imagick.v2/imagick/magick_wand_image.go:2202 +0x122 fp=0xc420148e88 sp=0xc420148e30
gopkg.in/gographics/imagick.v2/imagick.(*MagickWand).ReadImageBlob(0xc42021e8e0, 0xc42014c340, 0x194, 0x1a0, 0x194, 0x1a0)
        /go/src/gopkg.in/gographics/imagick.v2/imagick/magick_wand_image.go:2202 +0xcc fp=0xc420148ed8 sp=0xc420148e88
app.transformSvgToPng(0xc42014c340, 0x194, 0x1a0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/app/transform.go:15 +0xb0 fp=0xc420148f20 sp=0xc420148ed8

rax    0x17
rbx    0xc420024800
rcx    0x470865
rdx    0x17
rdi    0x2
rsi    0xa2fba2
rbp    0x8
rsp    0x7f8b54f51488
r8     0x7f8b54833a6d
r9     0x7f8b54f533e0
r10    0x7f8b54f4f3b8
r11    0x212
r12    0x7f8b54f544f8
r13    0x1ec97a0
r14    0x1f164c8
r15    0x0
rip    0x46ce22
rflags 0x212
cs     0x33
fs     0x0
gs     0x0
exit status 2
FAIL    app     0.034s
```

**Comment by justinfx** [comment]
What version of ImageMagick are you using? Also have you been able to reproduce this without a container? I have not tried building with musl before, so its a new variable in the equation. Others have found issues with certain types of containers because they were getting older versions of delegate plugins.

**Comment by eau-u4f** [comment]
I hit the exact same thing (not in imagick) but I guess it's go/cgo and musl related @bweston92 did you find what it was?
