### ISSUE TITLE
Shell script works fine, but the transformation go code reports an error

### ISSUE THREAD

**Issue by yangwenmai** [gographics/imagick#200]
This is worked.

```sh
convert test.png \( +clone -fill White -colorize 100%% -background Black -flatten -morphology Dilate Disk:7.5 -alpha Copy -fill White -colorize 100%% \) +swap -composite test_new.png
```

but I use `gographics/imagick`:

```
imagick.Initialize()
// Schedule cleanup
defer imagick.Terminate()

mw := imagick.NewMagickWand()
pw := imagick.NewPixelWand()

mwc := mw.Clone()
pw.SetColor("white")

pwo := imagick.NewPixelWand()

pwo.SetColor("rgb(100%,100%,100%)")
mwc.ColorizeImage(pw, pwo)

pw.SetColor("Black")
mwc.SetImageBackgroundColor(pw)

kernel_info, _ := imagick.NewKernelInfoBuiltIn(imagick.KERNEL_DISK, "7.5")
kernel_info.Scale(1.0, imagick.KERNEL_NORMALIZE_VALUE)

mwf := mwc.MergeImageLayers(imagick.IMAGE_LAYER_FLATTEN)
mwf.MorphologyImage(imagick.MORPHOLOGY_DILATE, 1, kernel_info)

mwf.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_COPY)

pw.SetColor("white")
pwo.SetColor("rgb(100%,100%,100%)")
mwf.ColorizeImage(pw, pwo)

mwfn := imagick.NewMagickWand()
mwfn.AddImage(mwf)
mwfn.AddImage(mwc)

mwfn.CompositeImage(mwf, imagick.COMPOSITE_OP_IN, true, 0, 0)
mwfn.WriteImage("./new_img.png")
```

occure error:

```sh
Assertion failed: (wand != (MagickWand *) NULL), function MagickMorphologyImage, file MagickWand/magick-image.c, line 7038.
SIGABRT: abort
PC=0x7fff6de6e2c6 m=7 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7fff6de6e2c6
stack: frame={sp:0x70000618fd38, fp:0x0} stack=[0x7000061102b0,0x70000618feb0)
000070000618fc38:  0000000000000000  0000000009afe000
000070000618fc48:  00007fff6de01f45  000070000618fcc0
000070000618fc58:  00007fff6df18bcb  0000000000000000
000070000618fc68:  000070000618fc90  000070000618fcd0
000070000618fc78:  0000000000000000  00007fff6de01f46
000070000618fc88:  000070000618fcd8  2d6b636967616d2f
000070000618fc98:  0000000005f658d6  0000000005f64a72
000070000618fca8:  0000000009afe000  0000000000001b7e
000070000618fcb8:  0000000005f64a58  000070000618fda0
000070000618fcc8:  00007fff6df17084  0000003000000030
000070000618fcd8:  000070000618fdb0  000070000618fcf0
000070000618fce8:  0000000000000000  0000000000000000
000070000618fcf8:  0000000000000000  0000000005f64a72
000070000618fd08:  0000000005f658d6  00007fffa0d2d240
000070000618fd18:  00007fffa0d2cca0  00007fff6ddb7bb8
000070000618fd28:  0000000000000000  000070000618fd70
000070000618fd38: <00007fff6df23bf1  0000700006190000
000070000618fd48:  000070000618fd88  0000000009afe028
000070000618fd58:  0000000009afe000  0000000000001b7e
000070000618fd68:  0000000005f64a58  000070000618fda0
000070000618fd78:  00007fff6ddd86a6  000070000618fda0
000070000618fd88:  00007fffffffffdf  ffffffff00000000
000070000618fd98:  0000000005f658d6  000070000618fde0
000070000618fda8:  00007fff6dda120d  000000c000d70000
000070000618fdb8:  0000000000000000  0000000000000004
000070000618fdc8:  0000000000000011  00000000063286d0
000070000618fdd8:  0000000000000001  000070000618fe20
000070000618fde8:  0000000005ee0cd7  000000c000d70000
000070000618fdf8:  000000c000d6fdc0  0000000000000004
000070000618fe08:  0000000000000011  000000c000d70000
000070000618fe18:  0000000000000000  000070000618fe50
000070000618fe28:  0000000004a5cda8  0000000004a5cd80
runtime: unknown pc 0x7fff6de6e2c6
stack: frame={sp:0x70000618fd38, fp:0x0} stack=[0x7000061102b0,0x70000618feb0)
000070000618fc38:  0000000000000000  0000000009afe000
000070000618fc48:  00007fff6de01f45  000070000618fcc0
000070000618fc58:  00007fff6df18bcb  0000000000000000
000070000618fc68:  000070000618fc90  000070000618fcd0
000070000618fc78:  0000000000000000  00007fff6de01f46
000070000618fc88:  000070000618fcd8  2d6b636967616d2f
000070000618fc98:  0000000005f658d6  0000000005f64a72
000070000618fca8:  0000000009afe000  0000000000001b7e
000070000618fcb8:  0000000005f64a58  000070000618fda0
000070000618fcc8:  00007fff6df17084  0000003000000030
000070000618fcd8:  000070000618fdb0  000070000618fcf0
000070000618fce8:  0000000000000000  0000000000000000
000070000618fcf8:  0000000000000000  0000000005f64a72
000070000618fd08:  0000000005f658d6  00007fffa0d2d240
000070000618fd18:  00007fffa0d2cca0  00007fff6ddb7bb8
000070000618fd28:  0000000000000000  000070000618fd70
000070000618fd38: <00007fff6df23bf1  0000700006190000
000070000618fd48:  000070000618fd88  0000000009afe028
000070000618fd58:  0000000009afe000  0000000000001b7e
000070000618fd68:  0000000005f64a58  000070000618fda0
000070000618fd78:  00007fff6ddd86a6  000070000618fda0
000070000618fd88:  00007fffffffffdf  ffffffff00000000
000070000618fd98:  0000000005f658d6  000070000618fde0
000070000618fda8:  00007fff6dda120d  000000c000d70000
000070000618fdb8:  0000000000000000  0000000000000004
000070000618fdc8:  0000000000000011  00000000063286d0
000070000618fdd8:  0000000000000001  000070000618fe20
000070000618fde8:  0000000005ee0cd7  000000c000d70000
000070000618fdf8:  000000c000d6fdc0  0000000000000004
000070000618fe08:  0000000000000011  000000c000d70000
000070000618fe18:  0000000000000000  000070000618fe50
000070000618fe28:  0000000004a5cda8  0000000004a5cd80

goroutine 7 [syscall]:
runtime.cgocall(0x4a5cd80, 0xc000d6fdc0, 0x29)
	/.../src/runtime/cgocall.go:128 +0x5e fp=0xc000d6fd88 sp=0xc000d6fd50 pc=0x400479e
gopkg.in/gographics/imagick.v3/imagick._Cfunc_MagickMorphologyImage(0x0, 0x4, 0x1, 0x63286d0, 0x0)
	_cgo_gotypes.go:6012 +0x4d fp=0xc000d6fdc0 sp=0xc000d6fd88 pc=0x48af3ad
gopkg.in/gographics/imagick.v3/imagick.(*MagickWand).MorphologyImage.func1(0x0, 0x4, 0x1, 0x63286d0, 0x0)
	/.../src/gopkg.in/gographics/imagick.v3/imagick/magick_wand_image.go:1576 +0xa1 fp=0xc000d6fdf8 sp=0xc000d6fdc0 pc=0x48da261
gopkg.in/gographics/imagick.v3/imagick.(*MagickWand).MorphologyImage(0xc00042c2e0, 0x4, 0x1, 0xc00000e028, 0x0, 0x0)
	/.../src/gopkg.in/gographics/imagick.v3/imagick/magick_wand_image.go:1576 +0x4e fp=0xc000d6fe30 sp=0xc000d6fdf8 pc=0x48c60de

rax    0x0
rbx    0x700006190000
rcx    0x70000618fd38
rdx    0x0
rdi    0xe03
rsi    0x6
rbp    0x70000618fd70
rsp    0x70000618fd38
r8     0x1b7e
r9     0xcccccccccccccccd
r10    0x0
r11    0x206
r12    0xe03
r13    0x9afe000
r14    0x6
r15    0x2d
rip    0x7fff6de6e2c6
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
exit status 2
```

I checked the code source.

```golang
func (mw *MagickWand) MergeImageLayers(method ImageLayerMethod) *MagickWand {
	ret := newMagickWand(C.MagickMergeImageLayers(mw.mw, C.LayerMethod(method)))
	runtime.KeepAlive(mw)
	return ret
}
```

`C.MagickMergeImageLayers(mw.mw, C.LayerMethod(method))` return a nil for those error.

But why return a nil?

**Comment by justinfx** [comment]
I am not sure which commit of Imagick v3 you are using against which version of ImageMagick 7, but it looks like your crash on the Go side starts here:
https://github.com/gographics/imagick/blob/im-7/imagick/magick_wand_image.go#L1582

```go
func (mw *MagickWand) MorphologyImage(method MorphologyMethod, iterations int, kernel *KernelInfo) error {
	ok := C.MagickMorphologyImage(mw.mw, C.MorphologyMethod(method), C.ssize_t(iterations), kernel.info)
	return mw.getLastErrorIfFailed(ok)
}
``` 

which means that the wand that is being passed to `MagickMorphologyImage` on the C side is `NULL`.
And you are correct that it would point to the previous call to `MergeImageLayers` returning that `NULL` wand. 

If we look at the source for that, it appears there are 2 cases where the C api would return `NULL`:
https://github.com/ImageMagick/ImageMagick/blob/7.0.8-1/MagickWand/magick-image.c#L6676

1. If your source wand has no images
1. The merge fails to return a valid mosaic image. But this is a bunch of nested calls that can each return NULL for an exception

Are you able to check for `nil` on the go side, and also check and print the value of [`MagickWand.getLastError()`](https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#PixelIterator.GetLastError) for your wands to see what went wrong in the C api?

**Comment by yangwenmai** [comment]
before call `mwc.MergeImageLayers`, mwc is not nil:
![image](https://user-images.githubusercontent.com/1710912/56775712-edc36000-67fa-11e9-8ae8-f9dd4f3e0db9.png)

after call `mwc.MergeImageLayers`, mwc is nil:
![image](https://user-images.githubusercontent.com/1710912/56775776-2feca180-67fb-11e9-9d9f-571ce66cfdad.png)

```golang
mwf := mwc.MergeImageLayers(imagick.IMAGE_LAYER_FLATTEN)
log.Infof("error: %+v", mwf.GetLastError())
```

print log:
```sh
Assertion failed: (wand != (const MagickWand *) NULL), function MagickGetException, file MagickWand/magick-wand.c, line 279.
```

**Comment by justinfx** [comment]
I was actually interested in the call to `mwc.getLastError()` *before* you try and call `mwc.MergeImageLayers` because it is going to abort at that point. 

```go
mwf := mwc.MergeImageLayers(imagick.IMAGE_LAYER_FLATTEN)
if err := mwf.GetLastError(); err != nil {
    panic(err)
}
mwf.MorphologyImage(imagick.MORPHOLOGY_DILATE, 1, kernel_info)
```

From the looks of your example code and the ImageMagick C source code, I am guessing the failure is because your `mwc` want has *zero* images to flatten.

**Comment by justinfx** [comment]
I just realised what is causing your issue. Your code example is not equivalent to your `convert` command because you are not reading in your source file and are dealing with a wand that contains no images:

Do this:
```go
mw := imagick.NewMagickWand()
if err := mw.ReadImage("test.png"); err != nil {
    panic(err)
}
```

That will fix your crash.

**Comment by yangwenmai** [comment]
Thanks, I see.
Can I Read from a `image.Image` ?

**Comment by justinfx** [comment]
It would probably be nice if we did have a convenience function for reading from an `image.Image`. If we did, it would likely iterate the source pixels from the `Image` and then use [`ImportImagePixels()`](https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.ImportImagePixels) to add the raw pixel data to the wand image.

But you can easily use something like the [`png.Encode()`](https://godoc.org/image/png#Encode) with a [`bytes.Buffer`](https://godoc.org/bytes#Buffer), and pass that to [`ReadImageBlob()`](https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.ReadImageBlob)
`ReadImageBlob` expects a reader to provide encoded image data (png, jpeg, etc) that it can decode. 
`ImportImagePixels` expects raw pixel data.

**Comment by yangwenmai** [comment]
OK, Thank you.

But I transaction this shell script is not work.

```shell
$ convert outff.png \( +clone -fill White -colorize 100%% -background Black -flatten -morphology Dilate Disk:7.5 -alpha Copy -fill White -colorize 100%% \) +swap -composite outff_new.png
```

Go 代码：
```golang
package main

import (
	"gopkg.in/gographics/imagick.v3/imagick"
)

func main() {
	// transaction this shell scripts:
	imagick.Initialize()
	// Schedule cleanup
	defer imagick.Terminate()

	mw := imagick.NewMagickWand()
	if err := mw.ReadImage("./outff.png"); err != nil {
		panic(err)
	}

	mwc := mw.Clone()

	pw := imagick.NewPixelWand()
	pwo := imagick.NewPixelWand()

	pw.SetColor("white")
	pwo.SetColor("rgb(100%,100%,100%)")

	mwc.ColorizeImage(pw, pwo)

	pw.SetColor("Black")
	mwc.SetImageBackgroundColor(pw)

	kernel_info, _ := imagick.NewKernelInfoBuiltIn(imagick.KERNEL_DISK, "7.5")
	kernel_info.Scale(1.0, imagick.KERNEL_NORMALIZE_VALUE)

	mwf := mwc.MergeImageLayers(imagick.IMAGE_LAYER_FLATTEN)
	mwf.MorphologyImage(imagick.MORPHOLOGY_DILATE, 1, kernel_info)
	mwf.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_COPY)

	pw.SetColor("white")
	pwo.SetColor("rgb(100%,100%,100%)")
	mwf.ColorizeImage(pw, pwo)

	mwfn := imagick.NewMagickWand()
	mwfn.AddImage(mwf)
	mwfn.AddImage(mw)

	mwfn.CompositeImage(mwf, imagick.COMPOSITE_OP_IN, true, 0, 0)
	mwfn.WriteImage("./outff_new.png")
}
```

**Comment by yangwenmai** [comment]
> It would probably be nice if we did have a convenience function for reading from an `image.Image`. If we did, it would likely iterate the source pixels from the `Image` and then use [`ImportImagePixels()`](https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.ImportImagePixels) to add the raw pixel data to the wand image.
> 
> But you can easily use something like the [`png.Encode()`](https://godoc.org/image/png#Encode) with a [`bytes.Buffer`](https://godoc.org/bytes#Buffer), and pass that to [`ReadImageBlob()`](https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.ReadImageBlob)
> `ReadImageBlob` expects a reader to provide encoded image data (png, jpeg, etc) that it can decode.
> `ImportImagePixels` expects raw pixel data.

I find the API `ReadImageBlob`

**Comment by justinfx** [comment]
I am not very experienced in ImageMagick convert operations. What is the output image supposed to look like? Is it supposed to composite a white circle over the original image?

**Comment by yangwenmai** [comment]
Yes, Like this:
![outff](https://user-images.githubusercontent.com/1710912/56782353-5ae5ee00-6819-11e9-932e-f85c2d017f9b.png)
![outff_new](https://user-images.githubusercontent.com/1710912/56782381-7b15ad00-6819-11e9-825a-638fe2e316b1.png)

**Comment by justinfx** [comment]
It looks like the kernel Scale operation was causing an issue with your mask. Once I removed that, it seems to work better. Also, it doesn't seem necessary to create a new wand with the images. This works for me:

```go
package main

import (
	"gopkg.in/gographics/imagick.v3/imagick"
)

func main() {
	imagick.Initialize()
	defer imagick.Terminate()

	mw := imagick.NewMagickWand()
	if err := mw.ReadImage("./outff.png"); err != nil {
		panic(err)
	}

	mwc := mw.Clone()

	pw := imagick.NewPixelWand()
	pwo := imagick.NewPixelWand()

	pw.SetColor("white")
	pwo.SetColor("white")

	mwc.ColorizeImage(pw, pwo)

	pw.SetColor("Black")
	mwc.SetImageBackgroundColor(pw)

	kernel_info, _ := imagick.NewKernelInfoBuiltIn(imagick.KERNEL_DISK, "7.5")
	//kernel_info.Scale(1.0, imagick.KERNEL_NORMALIZE_VALUE)

	mwf := mwc.MergeImageLayers(imagick.IMAGE_LAYER_FLATTEN)
	mwf.MorphologyImage(imagick.MORPHOLOGY_DILATE, 1, kernel_info)
	mwf.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_COPY)

	pw.SetColor("white")
	mwf.ColorizeImage(pw, pwo)
	
	mwf.CompositeImage(mw, imagick.COMPOSITE_OP_OVER, true, 0, 0)
	mwf.WriteImage("./outff_new.png")
}
```

**Comment by yangwenmai** [comment]
Thank you very much.
It's worked!

**Comment by justinfx** [comment]
Enjoy
