### ISSUE TITLE
image convert WriteImage fun error

### ISSUE THREAD

**Issue by charliecen** [gographics/imagick#285]
```go
        imagick.Initialize()
	defer imagick.Terminate()

	mw := imagick.NewMagickWand()
	err = mw.ReadImage(taskData.Source)
	if err != nil {
		return CodeImageReadError, err
	}
	err = mw.WriteImage(taskData.Dest)
	if err != nil {
		return CodeImageWriteError, err
	}
	
	code = CodeOK
	return
```

log error 

```sh
Segmentation fault (core dumped)
```

use gdb 

```sh
/app # gdb ./bin/convert/rpc/convert core.9614
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-alpine-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./bin/convert/rpc/convert...
[New LWP 9616]
[New LWP 9618]
[New LWP 9617]
[New LWP 9619]
[New LWP 9621]
[New LWP 9614]
[New LWP 9623]
[New LWP 9620]
[New LWP 9615]
[New LWP 9622]
Core was generated by `./bin/convert/rpc/convert -f bin/convert/rpc/convert.yaml'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000046578c in runtime.(*sigctxt).preparePanic (c=0xc000097298, sig=11, gp=0xc000006ea0) at /usr/local/go/src/runtime/signal_amd64.go:72
72		if shouldPushSigpanic(gp, pc, *(*uintptr)(unsafe.Pointer(sp))) {
[Current thread is 1 (LWP 9616)]
warning: File "/usr/local/go/src/runtime/runtime-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/local/go/src/runtime/runtime-gdb.py
line to your configuration file "/root/.config/gdb/gdbinit".
To completely disable this security protection add
--Type <RET> for more, q to quit, c to continue without paging--c
	set auto-load safe-path /
line to your configuration file "/root/.config/gdb/gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
(gdb) bt
#0  0x000000000046578c in runtime.(*sigctxt).preparePanic (c=0xc000097298, sig=11, gp=0xc000006ea0) at /usr/local/go/src/runtime/signal_amd64.go:72
#1  0x0000000000466909 in runtime.sighandler (sig=11, info=<optimized out>, ctxt=<optimized out>, gp=0xc000006ea0)
    at /usr/local/go/src/runtime/signal_unix.go:687
#2  0x0000000000466234 in runtime.sigtrampgo (sig=11, info=0xc0000974b0, ctx=0xc000097380) at /usr/local/go/src/runtime/signal_unix.go:479
#3  0x0000000000486aa6 in runtime.sigtramp () at /usr/local/go/src/runtime/sys_linux_amd64.s:359
#4  <signal handler called>
#5  0x00007fdd95a60b59 in ?? () from /usr/lib/libMagickCore-7.Q16HDRI.so.10
#6  0x00007fdd95a466eb in ?? () from /usr/lib/libMagickCore-7.Q16HDRI.so.10
#7  0x00007fdd95a476af in ?? () from /usr/lib/libMagickCore-7.Q16HDRI.so.10
#8  0x00007fdd95a47822 in ?? () from /usr/lib/libMagickCore-7.Q16HDRI.so.10
#9  0x00007fdd95a47982 in GetAuthenticPixels () from /usr/lib/libMagickCore-7.Q16HDRI.so.10
#10 0x00007fdd6db23167 in ?? () from /usr/lib/ImageMagick-7.1.0/modules-Q16HDRI/coders/png.so
#11 0x00007fdd6db2a457 in ?? () from /usr/lib/ImageMagick-7.1.0/modules-Q16HDRI/coders/png.so
#12 0x00007fdd95a7e79f in WriteImage () from /usr/lib/libMagickCore-7.Q16HDRI.so.10
#13 0x00007fdd95ce3622 in MagickWriteImage () from /usr/lib/libMagickWand-7.Q16HDRI.so.10
#14 0x000000000193cbeb in _cgo_82d526b279c4_Cfunc_MagickWriteImage (v=0xc000994a80) at /tmp/go-build/cgo-gcc-prolog:5027
#15 0x0000000000484b04 in runtime.asmcgocall () at /usr/local/go/src/runtime/asm_amd64.s:844
#16 0x0000000000432135 in runtime.SetFinalizer.func2 () at /usr/local/go/src/runtime/mfinal.go:450
#17 0x0000000000482c89 in runtime.systemstack () at /usr/local/go/src/runtime/asm_amd64.s:492
#18 0x0000000000000000 in ?? ()
(gdb)

```

write image dir is 777 permission
chomd 777 /data/ -R

**Comment by justinfx** [comment]
What linux distro and/or container image is this running under? And do you have more context around the test code?  Can you provide a complete runnable example so I can verify how its being execute?

**Comment by charliecen** [comment]
```sh
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.16.2
PRETTY_NAME="Alpine Linux v3.16"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
```

```dockerfile
FROM golang:alpine

ENV TZ Asia/Shanghai
ENV GOPROXY https://goproxy.cn,direct

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN apk update --no-cache \
    && apk add --no-cache tzdata busybox-extras

RUN apk add --no-cache build-base imagemagick-dev imagemagick

WORKDIR /app
```

**Comment by justinfx** [comment]
Thanks. If you search through the issue history for this project you will find that Alpine images have been the source of crashes in the past, because of the combination of the musl-compiled ImageMagick. Your Dockerfile example doesn't indicate where your application binary is being built (adding external from gcc/clang compiler, or built using musl).

See https://github.com/gographics/imagick/issues?q=is%3Aissue+alpine

https://github.com/gographics/imagick/issues/252

If you cant get it to reliably work in an Alpine image, you might consider switching to a tiny debian image (like minideb)

**Comment by charliecen** [comment]
> Thanks. If you search through the issue history for this project you will find that Alpine images have been the source of crashes in the past, because of the combination of the musl-compiled ImageMagick. Your Dockerfile example doesn't indicate where your application binary is being built (adding external from gcc/clang compiler, or built using musl).
> 
> See https://github.com/gographics/imagick/issues?q=is%3Aissue+alpine
> 
> #252
> 
> If you cant get it to reliably work in an Alpine image, you might consider switching to a tiny debian image (like minideb)

ok， I try it

**Comment by charliecen** [comment]
think you for reply
