### ISSUE TITLE
Magick Wand ReadImageFile fails

### ISSUE THREAD

**Issue by yayaayay** [gographics/imagick#46]
Attempting to use ReadImageFile results in the following error which cannot be prevented:

importer: wand/magick-image.c:8785: MagickReadImageFile: Assertion `file != (FILE *) ((void *)0)' failed.
SIGABRT: abort
PC=0x7f3039f405f8 m=3
signal arrived during cgo execution

Any help would be much appreciated!

**Comment by justinfx** [comment]
Can you please provide a complete reproduction example and also the version of ImageMagick and your platform?

**Comment by yayaayay** [comment]
Sure

Imagick Version
============
```
Version: ImageMagick 6.9.2-0 Q16 x86_64 2015-08-18 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP
Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jp2 jpeg lcms lqr ltdl lzma pangocairo png ps rsvg tiff webp wmf x xml zlib

```

Code To Reproduce
================
```go
package main

import (
  "github.com/gographics/imagick/imagick"
  "os"
)

func init() {
  imagick.Initialize()
}

func main() {
  file, err := os.Open("test.jpg")
  if err != nil {
    panic(err)
  }

  mw := imagick.NewMagickWand()
  defer mw.Destroy()

  mw.ReadImageFile(file)
}
```

Output
=====
```
$ go run main.go
main: wand/magick-image.c:8785: MagickReadImageFile: Assertion `file != (FILE *) ((void *)0)' failed.
SIGABRT: abort
PC=0x7efbfc6b65f8 m=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x41aa60, 0xc820055eb8, 0x0)
        /usr/lib/go/src/runtime/cgocall.go:120 +0x11b fp=0xc820055e88 sp=0xc820055e58
github.com/gographics/imagick/imagick._Cfunc_MagickReadImageFile(0x14de910, 0x0, 0x0)
        ??:0 +0x35 fp=0xc820055eb8 sp=0xc820055e88
github.com/gographics/imagick/imagick.(*MagickWand).ReadImageFile(0xc820034028, 0xc820034020, 0x0, 0x0)
        /app/go/src/github.com/gographics/imagick/imagick/magick_wand_image.go:2181 +0xde fp=0xc820055f00 sp=0xc820055eb8
main.main()
        /app/go/src/ReadImageFile/main.go:21 +0xc6 fp=0xc820055f50 sp=0xc820055f00
runtime.main()
        /usr/lib/go/src/runtime/proc.go:111 +0x2b0 fp=0xc820055fa0 sp=0xc820055f50
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820055fa8 sp=0xc820055fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

rax    0x0
rbx    0x7efbfd660000
rcx    0x7efbfc6b65f8
rdx    0x6
rdi    0x8be3
rsi    0x8be3
rbp    0x7efbfd22992f
rsp    0x7ffc09677068
r8     0x14e0790
r9     0xfeff092d63646b00
r10    0x8
r11    0x202
r12    0x2251
r13    0x7efbfd22b390
r14    0x3
r15    0x8
rip    0x7efbfc6b65f8
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
exit status 2

```

**Comment by justinfx** [comment]
Can you give #48 a test? It fixes the issue for me.

**Comment by yayaayay** [comment]
#48 seems to have fixed it! Thank you! The only issue is now that I get a bunch of deprecated warnings that I didn't before.

**Comment by justinfx** [comment]
The warnings are just from the master branch. I will merge this into master
and the im-6.8.9 branch.
